[project]
name = "smp-lab-documentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.0"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.17",
]
